[package]
name = "example-polygon-p2p"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
secp256k1 = { workspace = true, features = ["global-context", "std", "recovery"] }
tokio.workspace = true
reth-ethereum = { workspace = true, features = ["network"] }
reth-tracing.workspace = true
tokio-stream.workspace = true
reth-discv4 = { workspace = true, features = ["test-utils"] }
reth-network-p2p.workspace = true
alloy-eips.workspace = true
eyre.workspace = true
